workflows:
  android-release:
    name: MixPlaying Build
    max_build_duration: 60
    environment:
      vars:
        PROJECT_DIR: "app"
      flutter: stable
      java: 17
      android_signing:
        - keystore_reference
    scripts:
      - name: Dependencies install
        script: |
          cd $CM_BUILD_DIR
          chmod +x gradlew
          ./gradlew dependencies
      - name: Build Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your@email.com
