workflows:
  android-release:
    name: MixPlaying Release Build
    max_build_duration: 60
    environment:
      java: 17
      android_signing:
        - keystore_reference: your_keystore_reference
    scripts:
      - name: Prepare Gradle Wrapper
        script: |
          cd $CM_BUILD_DIR
          chmod +x ./gradlew
      - name: Clean Project
        script: |
          ./gradlew clean
      - name: Build Signed APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
